name: kg-idg
description: kg-idg-xxxxx
output_directory: output_data
graph_data:
  graph:
    node_path: ./xxxxs.tsv
    edge_path: ./xxxxx.tsv
    directed: false
    verbose: true
    nodes_column: id
    node_types_column: category
    default_node_type: biolink:NamedThing
    sources_column: subject
    destinations_column: object
    default_edge_type: biolink:related_to
embeddings:
  embedding_file_name: embeddings.tsv
  embedding_history_file_name: embedding_history.json
  node_embedding_params:
    node_embedding_method_name: SkipGram
    walk_length: 10
    batch_size: 512
    window_size: 3
    return_weight: 1.0
    explore_weight: 1.0
    iterations: 1
  tsne:
    tsne_file_name: embedding_tsne.png
    node_property_for_color: category
    scatter_params:
      marker: '.'
      s: 5

upload:
  s3_bucket: kg-hub-public-data
  s3_bucket_dir: xxxxx
  extra_args:
    ACL: public-read
